# NOTE: this is just for testing things on small amounts of data
normalisation_years: 
    - 2015
num_samples: 320000
latitude_step_size: 0.25
longitude_step_size: 0.25
pressure_levels:
    - 1000
input_fields: 
    - 2m_temperature
    - total_precipitation_6hr
    - land_sea_mask
    - temperature
target_fields:
    - 2m_temperature
derived_static_fields:
    - 
float16_fields:
    - 2m_temperature
    - 10m_v_component_of_wind
    - 10m_u_component_of_wind
    - total_precipitation_6hr
    - temperature
    - geopotential
    - u_component_of_wind
    - v_component_of_wind
    - vertical_velocity
    - specific_humidity
    - land_sea_mask
    - geopotential_at_surface
train_years:
    - 2015
validation_years:
    - 2015
normalisation_strategy:
paths:
  ml_data: '/network/group/aopp/predict/HMC005_ANTONIO_EERIE/ml_data'
  ERA5_stats: '/network/group/aopp/predict/HMC005_ANTONIO_EERIE/era5_stats'
  ERA5: '/network/group/aopp/predict/HMC005_ANTONIO_EERIE/era5'
  ERA5_AOPP: '/network/group/aopp/predict/HMC005_ANTONIO_EERIE/era5'
  ERA5_LOWRES: '/network/group/aopp/predict/HMC005_ANTONIO_EERIE/era5_1deg/bilinear'